# POWERLIFT PREDICTOR
### Predict the score for any one of the following three lifts, based on the other two:
- Squat
- Bench Press
- Deadlift

#### This Data Science analysis is performed on a [Powerlifting Dataset](https://www.kaggle.com/datasets/open-powerlifting/powerlifting-database) (pre-filtered for memory usage purposes), to perform Data preprocessing, Data cleaning, Feature Engineering, Exploratory Data Analysis (EDA), Data Visualization, Predictive Modeling, Model Evaluation, and Deployment

In [1]:
# IMPORTING LIBRARIES

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# LOADING DATASET

FILE_PATH = "./powerlifting-dataset.csv"

pldf_raw = pd.read_csv(FILE_PATH, index_col=0)

print("DATASET LOADED")
pldf_raw.shape

DATASET LOADED

(3043013, 6)

#### The raw dataset will remain unaltered and simply cloned into a new "working" dataframe

In [ ]:
# COPYING RAW DATASET INTO WORKING DATAFRAME

df = pldf_raw.copy()

df.head()

  Sex   Age  BodyweightKg  Best3SquatKg  Best3BenchKg  Best3DeadliftKg
0   F  33.0         58.30          80.0          60.0            107.5
1   F  43.0         73.10         105.0          67.5            110.0
2   M  15.5         67.40         100.0          62.5            105.0
3   M  35.0         66.65         137.5         122.5            170.0
4   M  26.5         72.45          90.0          50.0            125.0

#### Formatting the columns allows for easy reading and handling

In [ ]:
# RENAMING AND FORMAT COLUMNS

df.rename(
    columns = {
        "BodyweightKg": "WEIGHT",
        "Best3SquatKg": "SQUAT",
        "Best3BenchKg": "BENCH",
        "Best3DeadliftKg": "DEADLIFT"
    },
    inplace = True
)
df.rename(columns = lambda col: col.upper(), inplace=True)
df.head(5)

  SEX   AGE  WEIGHT  SQUAT  BENCH  DEADLIFT
0   F  33.0   58.30   80.0   60.0     107.5
1   F  43.0   73.10  105.0   67.5     110.0
2   M  15.5   67.40  100.0   62.5     105.0
3   M  35.0   66.65  137.5  122.5     170.0
4   M  26.5   72.45   90.0   50.0     125.0

#### After formatting the columns, each feature will be examined individually, starting with the descriptions (distrbutions, counts, values, etc)

In [6]:
# CHECKING "SEX" VALUES AND COUNTS

print(df["SEX"].value_counts(dropna=False))

SEX
M     2290122
F      752828
Mx         63
Name: count, dtype: int64

The "SEX" value "Mx" does not correspond to either Male or Female. Its purpose is unclear.
This issue can be approached by:
- Imputing "Mx" values -- using KNN or alternative
- Omitting the rows: losing 63 values (from over 3 million)
- Omitted the SEX column: losing an entire attribute due to a few unusual values

In [ ]:
# CHECKING "AGE" VALUES AND COUNTS

n_null_age = df[pd.isna(df["AGE"])].shape[0]
pct_null_age = np.round(n_null_age/df.shape[0]*100, 2)

print("Amount of missing AGE values:")
print(f"{n_null_age} of {df.shape[0]} ({pct_null_age}%)")

df["AGE"].describe().round().astype(int)

Amount of missing AGE values:
1070337 of 3043013 (35.17%)

count    1972676
mean          31
std           13
min            0
25%           20
50%           28
75%           38
max           98
Name: AGE, dtype: int64

The AGE column seems to have values of 0. 
Similar to the issue with the SEX column, this issue has a few possible approaches:
- Impute the invalid values
- Omit the rows
- Omit the entire AGE column

In [ ]:
# CHECKING "WEIGHT" VALUES AND 5-NUMBER SUMMARY

df["WEIGHT"].describe().round(2)

count    3004645.00
mean          84.17
std           22.63
min           10.00
25%           67.20
50%           81.95
75%           98.79
max          300.00
Name: WEIGHT, dtype: float64

The WEIGHT column seems to contain some values which are alarmingly low and alarmingly high.
The validity of these values must be confirmed via further analysis.