In [1]:
# IMPORTING LIBRARIES

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# LOADING DATASET

FILE_PATH = "./powerlifting-dataset.csv"

pldf_raw = pd.read_csv(FILE_PATH, index_col=0)

print("DATASET LOADED")
pldf_raw.shape

DATASET LOADED

(3043013, 6)

In [ ]:
# COPYING RAW DATASET INTO WORKING DATAFRAME

df = pldf_raw.copy()

df.head()

  Sex   Age  BodyweightKg  Best3SquatKg  Best3BenchKg  Best3DeadliftKg
0   F  33.0         58.30          80.0          60.0            107.5
1   F  43.0         73.10         105.0          67.5            110.0
2   M  15.5         67.40         100.0          62.5            105.0
3   M  35.0         66.65         137.5         122.5            170.0
4   M  26.5         72.45          90.0          50.0            125.0

In [ ]:
# RENAMING AND FORMAT COLUMNS

df.rename(
    columns = {
        "BodyweightKg": "WEIGHT",
        "Best3SquatKg": "SQUAT",
        "Best3BenchKg": "BENCH",
        "Best3DeadliftKg": "DEADLIFT"
    },
    inplace = True
)
df.rename(columns = lambda col: col.upper(), inplace=True)
df.head(5)

  SEX   AGE  WEIGHT  SQUAT  BENCH  DEADLIFT
0   F  33.0   58.30   80.0   60.0     107.5
1   F  43.0   73.10  105.0   67.5     110.0
2   M  15.5   67.40  100.0   62.5     105.0
3   M  35.0   66.65  137.5  122.5     170.0
4   M  26.5   72.45   90.0   50.0     125.0

In [6]:
# CHECKING "SEX" VALUES AND COUNTS

print(df["SEX"].value_counts(dropna=False))

SEX
M     2290122
F      752828
Mx         63
Name: count, dtype: int64

In [7]:
# CHECKING "AGE" VALUES AND COUNTS

n_null_age = df[pd.isna(df["AGE"])].shape[0]
pct_null_age = np.round(n_null_age/df.shape[0]*100, 2)

print("Amount of missing AGE values:")
print(f"{n_null_age} of {df.shape[0]} ({pct_null_age}%)")

df["AGE"].describe().round().astype(int)

Amount of missing AGE values:
1070337 of 3043013 (35.17%)

count    1972676
mean          31
std           13
min            0
25%           20
50%           28
75%           38
max           98
Name: AGE, dtype: int64