In [45]:
# IMPORTING LIBRARIES

import numpy as np
import pandas as pd

In [46]:
# LOADING DATASET

FILE_PATH = "./powerlifting-dataset.csv"

pldf_raw = pd.read_csv(FILE_PATH, index_col=0)

print("DATASET LOADED")
pldf_raw.shape

DATASET LOADED

(3043013, 6)

In [47]:
pldf_raw.head(5)

  Sex   Age  BodyweightKg  Best3SquatKg  Best3BenchKg  Best3DeadliftKg
0   F  33.0         58.30          80.0          60.0            107.5
1   F  43.0         73.10         105.0          67.5            110.0
2   M  15.5         67.40         100.0          62.5            105.0
3   M  35.0         66.65         137.5         122.5            170.0
4   M  26.5         72.45          90.0          50.0            125.0

In [48]:
# COPY RAW DATASET INTO WORKING DATAFRAME

df = pldf_raw.copy()

df.head()

  Sex   Age  BodyweightKg  Best3SquatKg  Best3BenchKg  Best3DeadliftKg
0   F  33.0         58.30          80.0          60.0            107.5
1   F  43.0         73.10         105.0          67.5            110.0
2   M  15.5         67.40         100.0          62.5            105.0
3   M  35.0         66.65         137.5         122.5            170.0
4   M  26.5         72.45          90.0          50.0            125.0

In [50]:
# RENAME AND FORMAT COLUMNS

df.rename(
    columns = {
        "BodyweightKg": "WEIGHT",
        "Best3SquatKg": "SQUAT",
        "Best3BenchKg": "BENCH",
        "Best3DeadliftKg": "DEADLIFT"
    },
    inplace = True
)
df.rename(columns = lambda col: col.upper(), inplace=True)
df.head(5)

  SEX   AGE  WEIGHT  SQUAT  BENCH  DEADLIFT
0   F  33.0   58.30   80.0   60.0     107.5
1   F  43.0   73.10  105.0   67.5     110.0
2   M  15.5   67.40  100.0   62.5     105.0
3   M  35.0   66.65  137.5  122.5     170.0
4   M  26.5   72.45   90.0   50.0     125.0

In [ ]:
# CHECKING "SEX" VALUES AND COUNTS

print(df["SEX"].value_counts(dropna=False))

SEX
M     2290122
F      752828
Mx         63
Name: count, dtype: int64
AGE
NaN     1070337
17.5      55923
18.5      49631
16.5      49431
22.5      48311
         ...
95.5          3
94.5          2
97.5          2
96.5          1
98.0          1
Name: count, Length: 198, dtype: int64